# Generated by Django 4.1.4 on 2022-12-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
