# Generated by Django 4.1.4 on 2022-12-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_video_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
